import {
  Dashboard,
  LoginPage,
  ServiceManagement,
  ServicesPage,
  AddOnServicesPage,
  CategoriesPage,
  PreferencesPage,
  ServiceDashboardPage,
  ConfigureServicesPage,
  CustomerManagement,
  CustomerSupport,
  DeleteAccountReasons,
  CustomerDetails,
  ShopDetails,
  DriverManagement,
  DriverDetails,
  ZoneManagement,
  EmployeeManagement,
  EmployeeDetails,
  EditEmployee,
  RolePermission,
  Blogs,
  FAQ,
  EditCustomer,
  AllOrders,
  CompleteOrders,
  PendingOrders,
  CancelledOrders,
  OnHoldOrders,
  PaymentFailures,
  ActionRequiredOrders,
  EditOrder,
  OrderDetails,
  CountriesAndCities,
  CountriesPage,
  CitiesPage,
  PoliciesManagement,
  CancellationPolicy,
  OverallPolicies,
  NoShowPolicy,
  ReschedulePolicy,
  PlatformOperationalHours,
  PromoCodesPage,
  BannersPage,
  NotifyLogsPage,
  FcmDebugPage,
  SendNotificationsPage,
  AdminNotificationSettingsPage,
} from "../routes/AsyncComponent";

export const privateRoutes = [
  { path: "/", element: Dashboard, resourceKey: "dashboard_Page" },
  {
    path: "/services-management",
    element: ServiceManagement,
    resourceKey: "services_management_Page",
  },
  {
    path: "/services-management/dashboard",
    element: ServiceDashboardPage,
    resourceKey: "service_dashboard_Page",
  },
  {
    path: "/services-management/services",
    element: ServicesPage,
    resourceKey: "services_page",
  },
  {
    path: "/services-management/add-on-services",
    element: AddOnServicesPage,
    resourceKey: "add_on_services_page",
  },
  {
    path: "/services-management/categories",
    element: CategoriesPage,
    resourceKey: "categories_page",
  },
  {
    path: "/services-management/preferences",
    element: PreferencesPage,
    resourceKey: "preferences_page",
  },
  {
    path: "/services-management/configure-services",
    element: ConfigureServicesPage,
    resourceKey: "configure_services_page",
  },
  {
    path: "/customer-management",
    element: CustomerManagement,
    resourceKey: "customer_management_Page",
  },
  {
    path: "/customer-support",
    element: CustomerSupport,
    resourceKey: "customer_support_page",
  },
  {
    path: "/notify-logs",
    element: NotifyLogsPage,
    resourceKey: "notify_call_logs_page",
  },
  {
    path: "/fcm-debug",
    element: FcmDebugPage,
    resourceKey: "fcm_push_debug_page",
  },
  {
    path: "/send-notifications",
    element: SendNotificationsPage,
    resourceKey: "send_notifications_page",
  },
  {
    path: "/admin-notification-settings",
    element: AdminNotificationSettingsPage,
    resourceKey: "admin_notification_settings_page",
  },
  {
    path: "/delete-account-reasons",
    element: DeleteAccountReasons,
    resourceKey: "delete_account_reasons_page",
  },
  {
    path: "/customer-management/details/:id",
    element: CustomerDetails,
    resourceKey: "customer_details_Page",
  },
  {
    path: "/customer-management/edit/:id",
    element: EditCustomer,
    resourceKey: "customer_edit_Page",
  },
  {
    path: "/driver-management",
    element: DriverManagement,
    resourceKey: "driver_management_Page",
  },
  {
    path: "/driver-management/details/:id",
    element: DriverDetails,
    resourceKey: "driver_details_Page",
  },
  {
    path: "/zone-management",
    element: ZoneManagement,
    resourceKey: "zone_management_Page",
  },
  {
    path: "/employee-management",
    element: EmployeeManagement,
    resourceKey: "employee_management_Page",
  },
  {
    path: "/employee-management/details/:id",
    element: EmployeeDetails,
    resourceKey: "employee_details_Page",
  },
  {
    path: "/employee-management/edit/:id",
    element: EditEmployee,
    resourceKey: "employee_edit_Page",
  },
  {
    path: "/role-permission",
    element: RolePermission,
    resourceKey: "role_permission_page",
  },
  {
    path: "/blogs",
    element: Blogs,
    resourceKey: "blogs_Page",
  },
  {
    path: "/faq",
    element: FAQ,
    resourceKey: "faq_Page",
  },
  {
    path: "/orders/action-required",
    element: ActionRequiredOrders,
    resourceKey: "order_action-required_Page",
  },
  {
    path: "/orders/all-orders",
    element: AllOrders,
    resourceKey: "order_all-orders_Page",
  },
  {
    path: "/orders/complete-orders",
    element: CompleteOrders,
    resourceKey: "order_complete-orders_Page",
  },
  {
    path: "/orders/pending-orders",
    element: PendingOrders,
    resourceKey: "order_pending-orders_Page",
  },
  {
    path: "/orders/cancel-orders",
    element: CancelledOrders,
    resourceKey: "order_cancel-orders_Page",
  },
  {
    path: "/orders/on-hold-orders",
    element: OnHoldOrders,
    resourceKey: "order_on-hold-orders_Page",
  },
  {
    path: "/orders/payment-failures",
    element: PaymentFailures,
    resourceKey: "order_payment-failures_Page",
  },
  {
    path: "/orders/edit/:id",
    element: EditOrder,
    resourceKey: "order_edit_Page",
  },
  {
    path: "/orders/details/:id",
    element: OrderDetails,
    resourceKey: "order_details_Page",
  },
  {
    path: "/countries-cities",
    element: CountriesAndCities,
    resourceKey: "countries_cities_Page",
  },
  {
    path: "/countries-cities/countries",
    element: CountriesPage,
    resourceKey: "countries_page",
  },
  {
    path: "/countries-cities/cities",
    element: CitiesPage,
    resourceKey: "cities_page",
  },
  {
    path: "/policies-management",
    element: PoliciesManagement,
    resourceKey: "policies_management_page",
  },
  {
    path: "/policies-management/overall-policies",
    element: OverallPolicies,
    resourceKey: "overall_policies_page",
  },
  {
    path: "/policies-management/cancellation-policy",
    element: CancellationPolicy,
    resourceKey: "cancellation_policy_page",
  },
  {
    path: "/policies-management/no-show-policy",
    element: NoShowPolicy,
    resourceKey: "no_show_policy_page",
  },
  {
    path: "/policies-management/reschedule-policy",
    element: ReschedulePolicy,
    resourceKey: "reschedule_policy_page",
  },
  {
    path: "/policies-management/platform-operational-hours",
    element: PlatformOperationalHours,
    resourceKey: "platform_operational_hours_page",
  },
  {
    path: "/promotion/promo-codes",
    element: PromoCodesPage,
    resourceKey: "promotion_promo_codes_page",
  },
  {
    path: "/promotion/banners",
    element: BannersPage,
    resourceKey: "promotion_banners_page",
  },
];

export const publicRoutes = [
  {
    path: "/login",
    element: LoginPage,
    resourceKey: "login_page",
  },
];
